# Site settings
title: PRML


email: "prat8897@gmail.com"
url: "http://norman3.github.io"
github_url: "https://github.com/prat8897/prml"
github_editurl: "/blob/gh-pages"
github_profile: "https://github.com/prat8897"
baseurl: "/prml"
disqus_shortname: prat8897

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
